FROM davidv27/gh-actions:latest
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y --profile minimal --default-toolchain stable
RUN apt-get install -y nodejs build-essential make gcc

